name: Build-vipPanel-Macro
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile EXE
        run: |
          g++ main.cpp -o vipPanel_FF.exe -static -luser32 -lgdi32 -mwindows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: vipPanel-FF-Cua-Anh-Trai
          path: vipPanel_FF.exe
